### ISSUE TITLE
[SOLVED] Strange behavior of buttons on materialize branch

### ISSUE THREAD

**Issue by ovidb** [Differential/meteor-boilerplate#59]
There seems to be a bug in the way waves-effects work on buttons

If you click'em multiple times (or click and rapidly hover out) multiple waves will be applied. The button becomes lighter and lighter in color but it doesn't go back to the previous original shade.

If you click and wait (hover) until the wave finishes then it works.

I've also noticed that if you only hover the button without clicking, the shade is restored, level by level, until the original color of the background is applied.

You can check it out here:
![ezgif com-crop](https://cloud.githubusercontent.com/assets/1531356/6893277/4f2db6ea-d6d4-11e4-8f26-f5fe6ad48357.gif)
(don't know if animated gifs work on github :D)

or here:
http://giphy.com/gifs/3oEduRE4sMHjCTfGso

Update: 
With a fresh meteor created app and the materialize:materialize package this behavior isn't noticed.

**Comment by laurentpayot** [comment]
I have the exact same problem here. Using the official materialize package or the compiled source scss and javascript files makes no difference.

**Comment by antarexis** [comment]
OK so I found a solution.

It seems that since the materialize:materialize package is included if you just remove ```materialize.js``` from ```/client/compatibility``` everything works!

I won't close it though until this will be fixed

**Comment by laurentpayot** [comment]
:+1: Thanks antarexis! Removing materialize.js fixed it. It's strange because I don't use the materialize:materialize package, but I guess other packages such as useraccounts:materialize or gildaspk:autoform-materialize added it.
I upgraded to the new 0.96.1 materialize sass zip file and the materialize.js file is gone from the archive, thus it worked too.

(PS: upgrading to 0.96.1 introduced lots of bugs such as weird dropdown menus, but at least this strange button behavior is fixed)

**Comment by antarexis** [comment]
Glad it worked! :D

**Comment by mordka** [comment]
I was investigating this problem as well. Thanks @antarexis, you saved me few hours :+1:
